server:
  port: 9999

spring:
  datasource:
    username: root
    password: nnBeautiful@1117
    url: jdbc:mysql:///xdb
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.caleb: debug

